### ISSUE TITLE
There are some minor outdated pieces in the tutorial, but major with the register user.

### ISSUE THREAD

**Issue by markparz** [IBM/Blockchain-for-maintaining-Digital-Assets#9]
This pattern is not working getting the following error:

 { "message": "The \"options.ca\" property must be one of type string, Buffer, TypedArray, or DataView. Received type object", "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"options.ca\" property must be one of type string, Buffer, TypedArray, or DataView. Received type object\n at validateKeyCert (_tls_common.js:82:11)\n at Object.createSecureContext (_tls_common.js:114:9)\n at Object.connect (_tls_wrap.js:1160:48)\n at Agent.createConnection (https.js:120:22)\n at Agent.createSocket (_http_agent.js:227:26)\n at Agent.addRequest (_http_agent.js:185:10)\n at new ClientRequest (_http_client.js:258:16)\n at Object.request (https.js:289:10)\n at Promise (/Users/parzy/src/assetApp/Blockchain-for-maintaining-Digital-Assets/web-app/server/node_modules/fabric-client/node_modules/fabric-ca-client/lib/FabricCAClient.js:306:37)\n at new Promise (<anonymous>)" }

**Comment by bmos299** [comment]
I got the same error trying to register a user. `
        // Get the CA client object from the gateway for interacting with the CA.
        const ca = gateway.getClient().getCertificateAuthority();
        const adminIdentity = gateway.getCurrentIdentity();

        // Register the user, enroll the user, and import the new identity into the wallet.
        const secret = await ca.register({ affiliation: 'org1', enrollmentID: emailAddress, role: 'client' }, adminIdentity);

        const enrollment = await ca.enroll({ enrollmentID: emailAddress, enrollmentSecret: secret });`

**Comment by bmos299** [comment]
In network.js.  It looks almost just like the fabcar tutorial in fabric-samples.

**Comment by sandhya-nayak** [comment]
@markparz @bmos299 Some changes were made to the code recently. There's also a pending PR with some updates to the ReadMe. Can you try again with these changes and see if you still run into errors?

**Comment by sandhya-nayak** [comment]
@bmos299 @markparz You can also look at this fix https://github.com/IBM/evote/issues/41#issuecomment-651925530
